hydra:
    run:
        dir: "outputs/${exp}/${run}"

defaults:
  - model: idr
  - dataset: sample
  - _self_

seed: 42
project_name: "VOLSDF_cam_norm"
exp: ${dataset.train.dataset}
run: ${dataset.train.subject}