hydra:
    run:
        dir: "outputs/${exp}/${run}"

defaults:
  - model: model_w_bg
  - dataset: 3DPW # hi4d # video # 3DPW
  - _self_

seed: 42
project_name: "VOLSDF_cam_norm"
exp: ${dataset.train.dataset}
run: ${dataset.train.subject}