train:
    dataset: BuffMono
    subject: "buff_mono_new_init"

    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8

    data_dir : buff_mono_new/
    num_sample : 2048

valid:
    dataset: "BuffMonoVal"
    subject: "buff_mono_new_init"
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 0

    data_dir : buff_mono_new/
    num_sample : -1
    pixel_per_batch: 12000

test:
    dataset: "BuffMonoTest"
    subject: "buff_mono_new_init"
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : buff_mono_new/
    num_sample : -1
    pixel_per_batch: 6000