train:
    dataset: BuffMonoSeg
    subject: "debug_buffmono_weighted"

    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8

    data_dir : buff_mono_seg/
    num_sample : 256 # 2048

valid:
    dataset: "BuffMonoSegVal"
    subject: "debug_buffmono_weighted"
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : buff_mono_seg/
    num_sample : -1
    pixel_per_batch: 360 # 12000

# test:
#     dataset: "BuffMonoSegTest"
#     subject: "with_parsing"
#     image_id: 0

#     batch_size: 1
#     drop_last: False
#     shuffle: False
#     worker: 8

#     data_dir : buff_mono_seg/
#     num_sample : -1
#     pixel_per_batch: 12000