train:
    dataset: BuffMonoSeg
    subject: "buffmono_smpl_debug_radius"

    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8

    data_dir : buff_mono_seg/
    num_sample : 512 # 2048

valid:
    dataset: "BuffMonoSegVal"
    subject: "buffmono_smpl_debug_radius"
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : buff_mono_seg/
    num_sample : -1
    pixel_per_batch: 512 # 12000

# test:
#     dataset: "BuffMonoSegTest"
#     subject: "with_parsing"
#     image_id: 0

#     batch_size: 1
#     drop_last: False
#     shuffle: False
#     worker: 8

#     data_dir : buff_mono_seg/
#     num_sample : -1
#     pixel_per_batch: 12000