train:
    dataset: Cape
    subject: "buff_multi_views"

    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8

    data_dir : buff_new/
    num_sample : 1024

valid:
    dataset: "CapeVal"
    subject: "buff_multi_views"
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : buff_new/
    num_sample : -1
    pixel_per_batch: 1024

test:
    dataset: "CapeTest"
    subject: "buff_multi_views"
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : buff_new/
    num_sample : -1
    pixel_per_batch: 2048