train:
    dataset: Cape
    subject: "buff_one_image"

    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8

    data_dir : buff_one_image/
    num_sample : 2048

valid:
    dataset: "CapeVal"
    subject: "buff_one_image"
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : buff_one_image/
    num_sample : -1
    pixel_per_batch: 12000

test:
    dataset: "CapeTest"
    subject: "buff_one_image"
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : buff_one_image/
    num_sample : -1
    pixel_per_batch: 2048