train:
    dataset: Hi4D
#    subject: "courtyard_shakeHands_00_no_pose_condition_interpenetration_loss_idr"
    subject: "cycle_dance_SAM_ratio75_smpl_depth_map_10_samGT_personid"
    start_frame: 0
    end_frame: 180
    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8
    num_person: 2
    data_dir : cycle_dance/
    num_sample : 512
    using_SAM: True
    ratio_uncertain: 0.75

valid:
    dataset: "Hi4DVal"
#    subject: "courtyard_shakeHands_00_no_pose_condition_interpenetration_loss_idr"
    subject: "cycle_dance_SAM_ratio75_smpl_depth_map_10_samGT_personid"
    start_frame: 0
    end_frame: 180
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : cycle_dance/
    num_sample : -1
    pixel_per_batch: 1536
    using_SAM: True
    ratio_uncertain: 0.75

test:
    dataset: "Hi4DTest"
#    subject: "courtyard_shakeHands_00_no_pose_condition_interpenetration_loss_idr"
    subject: "cycle_dance_SAM_ratio75_smpl_depth_map_10_samGT_personid"
    start_frame: 0
    end_frame: 180
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 0

    data_dir : cycle_dance/
    num_sample : 0
    pixel_per_batch: 1536
    using_SAM: True
    ratio_uncertain: 0.75