train:
    dataset: Hi4D
#    subject: "courtyard_shakeHands_00_no_pose_condition_interpenetration_loss_idr"
    subject: "Hi4D_pair19_piggyback19_4_sam_delay_depth_2_noshare_sam"
    start_frame: 0
    end_frame: 150
    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8
    num_person: 2
    data_dir : pair19_piggyback19_vitpose_4/
    num_sample : 512
    using_SAM: True

valid:
    dataset: "Hi4DVal"
#    subject: "courtyard_shakeHands_00_no_pose_condition_interpenetration_loss_idr"
    subject: "Hi4D_pair19_piggyback19_4_sam_delay_depth_2_noshare_sam"
    start_frame: 0
    end_frame: 150
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : pair19_piggyback19_vitpose_4/
    num_sample : -1
    pixel_per_batch: 512
    using_SAM: True

test:
    dataset: "Hi4DTest"
#    subject: "courtyard_shakeHands_00_no_pose_condition_interpenetration_loss_idr"
    subject: "Hi4D_pair19_piggyback19_4_sam_delay_depth_2_noshare_sam"
    start_frame: 0
    end_frame: 150
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 0

#    data_dir : pair19_piggyback19_vitpose_4/
    data_dir : Hi4D_pair19_piggyback19/
    num_sample : 0
    pixel_per_batch: 1024
    using_SAM: True

    novel_view: 88
    current_view: 4
    pair: 'pair19'
    action: 'piggyback19'