train:
    dataset: Hi4D
#    subject: "courtyard_shakeHands_00_no_pose_condition_interpenetration_loss_idr"
    subject: "Hi4D_pair16_jump16_4_sam_delay_depth_loop_align_vitpose_end_2_edge_noshare"
    start_frame: 0
    end_frame: 90
    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8
    num_person: 2
    data_dir : pair16_jump16_vitpose_4/
    num_sample : 512
    using_SAM: True
    edge_sampling: True

valid:
    dataset: "Hi4DVal"
#    subject: "courtyard_shakeHands_00_no_pose_condition_interpenetration_loss_idr"
    subject: "Hi4D_pair16_jump16_4_sam_delay_depth_loop_align_vitpose_end_2_edge_noshare"
    start_frame: 0
    end_frame: 90
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : pair16_jump16_vitpose_4/
    num_sample : -1
    pixel_per_batch: 1024
    using_SAM: True

test:
    dataset: "Hi4DTest"
#    subject: "courtyard_shakeHands_00_no_pose_condition_interpenetration_loss_idr"
    subject: "Hi4D_pair16_jump16_4_sam_delay_depth_loop_align_vitpose_end_2_edge_noshare"
    start_frame: 0
    end_frame: 90
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 0

#    data_dir : pair16_jump16_vitpose_4/
    data_dir : Hi4D_pair16_jump16/
    num_sample : 0
    pixel_per_batch: 1024
    using_SAM: True
#
    novel_view: 88
    current_view: 4
    pair: 'pair16'
    action: 'jump16'