train:
    dataset: MoCap
    subject: "juan_waving_wo_bg"

    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8

    data_dir : mocap_juan_waving/
    num_sample : 512

valid:
    dataset: "MoCapVal"
    subject: "juan_waving_wo_bg"
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : mocap_juan_waving/
    num_sample : -1
    pixel_per_batch: 512

# test:
#     dataset: "CapeTest"
#     subject: "buff_multi_views"
#     image_id: 0

#     batch_size: 1
#     drop_last: False
#     shuffle: False
#     worker: 8

#     data_dir : buff_new/
#     num_sample : -1
#     pixel_per_batch: 512