train:
    dataset: MoCap
    subject: "ernst_test"

    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8

    data_dir : mocap_ernst/
    num_sample : 512

valid:
    dataset: "MoCapVal"
    subject: "ernst_test"
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 0

    data_dir : mocap_ernst/
    num_sample : -1
    pixel_per_batch: 512

test:
    dataset: "MoCapTest"
    subject: "ernst_test"
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : mocap_ernst/
    num_sample : -1
    pixel_per_batch: 512