train:
    dataset: MoCap
    subject: "otmar_waiving_w_bg_net_w_reg"

    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8

    data_dir : mocap_otmar_waiving/
    num_sample : 512

valid:
    dataset: "MoCapVal"
    subject: "otmar_waiving_w_bg_net_w_reg"
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 0

    data_dir : mocap_otmar_waiving/
    num_sample : -1
    pixel_per_batch: 512

test:
    dataset: "MoCapTest"
    subject: "otmar_waiving_w_bg_net_w_reg"
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : mocap_otmar_waiving/
    num_sample : -1
    pixel_per_batch: 512