train:
    dataset: MoCap
    subject: "juan_waving_sphere_sdf_all_x"

    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8

    data_dir : mocap_juan_waving/
    num_sample : 512

valid:
    dataset: "MoCapVal"
    subject: "juan_waving_sphere_sdf_all_x"
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : mocap_juan_waving/
    num_sample : -1
    pixel_per_batch: 512

test:
    dataset: "MoCapTest"
    subject: "juan_waving_sphere_sdf_all_x"
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : mocap_juan_waving/
    num_sample : -1
    pixel_per_batch: 512