train:
    dataset: PosePrior
    subject: "smpl_init_male_256"

    batch_size: 8
    drop_last: False
    shuffle: True
    worker: 8

    data_dir : home/
    num_sample : 2048

valid:
    dataset: "PosePriorVal"
    subject: "smpl_init_male_256"
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : home/
    num_sample : -1
    pixel_per_batch: 8192