train:
    dataset: Real
    subject: "pss_sphere"

    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 0

    data_dir : pss_resized_new/
    num_sample : 2048

valid:
    dataset: "RealVal"
    subject: "pss_sphere"
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 0

    data_dir : pss_resized_new/
    num_sample : -1
    pixel_per_batch: 12000