train:
    dataset: Sample
    subject: "debug_body_normalize"

    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 4

    data_dir : sample_body/
    num_sample : 2048 # 1000

valid:
    dataset: "SampleVal"
    subject: "debug_body_normalize"
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 0

    data_dir : sample_body/
    num_sample : -1
    pixel_per_batch: 2048 # 2000