train:
    dataset: Sample
    subject: "debug_tcnn_p16"

    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 4

    data_dir : sample_body/
    num_sample : 4096 # 1000

valid:
    dataset: "SampleVal"
    subject: "debug_tcnn_p16"
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 0

    data_dir : sample_body/
    num_sample : -1
    pixel_per_batch: 4096 # 2000

test:
    dataset: "SampleTest"
    subject: "debug_tcnn_p16"
    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 4

    data_dir : sample_body/
    num_sample : -1
    pixel_per_batch: 16384 # 2000