train:
    dataset: Sample
    subject: "head"

    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 4

    data_dir : sample_head/
    num_sample : 2048

valid:
    dataset: "SampleVal"
    subject: "head"
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 4

    data_dir : sample_head/
    num_sample : -1
    pixel_per_batch: 8192