train:
    dataset: Hi4D
#    subject: "courtyard_shakeHands_00_no_pose_condition_interpenetration_loss_idr"
    subject: "sydney_sam_delay_depth_loop_noshare"
    start_frame: 0
    end_frame: 156
    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8
    num_person: 5
    data_dir : sydney/
    num_sample : 1024
    using_SAM: True

valid:
    dataset: "Hi4DVal"
#    subject: "courtyard_shakeHands_00_no_pose_condition_interpenetration_loss_idr"
    subject: "sydney_sam_delay_depth_loop_noshare"
    start_frame: 0
    end_frame: 156
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : sydney/
    num_sample : -1
    pixel_per_batch: 1024
    using_SAM: True

test:
    dataset: "Hi4DTest"
#    subject: "courtyard_shakeHands_00_no_pose_condition_interpenetration_loss_idr"
    subject: "sydney_sam_delay_depth_loop_noshare"
    start_frame: 0
    end_frame: 156
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 0

    data_dir : sydney/
    num_sample : 0
    pixel_per_batch: 1024
    using_SAM: True