train:
    dataset: Hi4D
#    subject: "courtyard_shakeHands_00_no_pose_condition_interpenetration_loss_idr"
    subject: "taichi03_sam_delay_depth20_loop_2_0pose"
    start_frame: 0
    end_frame: 58
    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8
    num_person: 2
    data_dir : taichi03/
    num_sample : 512
    using_SAM: True

valid:
    dataset: "Hi4DVal"
#    subject: "courtyard_shakeHands_00_no_pose_condition_interpenetration_loss_idr"
    subject: "taichi03_sam_delay_depth20_loop_2_0pose"
    start_frame: 0
    end_frame: 58
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : taichi03/
    num_sample : -1
    pixel_per_batch: 768
    using_SAM: True

test:
    dataset: "Hi4DTest"
#    subject: "courtyard_shakeHands_00_no_pose_condition_interpenetration_loss_idr"
    subject: "taichi03_sam_delay_depth20_loop_2_0pose"
    start_frame: 0
    end_frame: 58
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 0

    data_dir : taichi03/
    num_sample : 0
    pixel_per_batch: 1024
    using_SAM: True