train:
    dataset: ThreeDPW
    subject: "seattle_wo_disp_freeze_20_every_20_opt_pose_split"
    start_frame: 0
    end_frame: 41
    exclude_frames: [2, 7, 12, 17]
    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8

    data_dir : seattle/
    num_sample : 512 # 2048 256

valid:
    dataset: "ThreeDPWVal"
    subject: "seattle_wo_disp_freeze_20_every_20_opt_pose_split"
    start_frame: 0
    end_frame: 41
    exclude_frames: [2, 7, 12, 17]
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : seattle/
    num_sample : -1
    pixel_per_batch: 2048  # 16000 256

test:
    dataset: "ThreeDPWTest"
    subject: "seattle_wo_disp_freeze_20_every_20_opt_pose_split"
    start_frame: 0
    end_frame: 41
    exclude_frames: 'none'
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 0

    data_dir : seattle/
    num_sample : -1
    pixel_per_batch: 2048