train:
    dataset: ThreeDPW
    subject: "Invisible_disp_hann_step_for_binary"
    start_frame: 0
    end_frame: 658
    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8

    data_dir : Invisible/
    num_sample : 512 # 2048 256

valid:
    dataset: "ThreeDPWVal"
    subject: "Invisible_disp_hann_step_for_binary"
    start_frame: 0
    end_frame: 658
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : Invisible/
    num_sample : -1
    pixel_per_batch: 2048  # 16000 256

test:
    dataset: "ThreeDPWTest"
    subject: "Invisible_disp_hann_step_for_binary"
    start_frame: 0
    end_frame: 658
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : Invisible/
    num_sample : -1
    pixel_per_batch: 2048