train:
    dataset: ThreeDPW
    subject: "debug_volsdf"

    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8

    data_dir : courtyard_jumpBench_01/
    num_sample : 512 # 2048 256

valid:
    dataset: "ThreeDPWVal"
    subject: "debug_volsdf"
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : courtyard_jumpBench_01/
    num_sample : -1
    pixel_per_batch: 512  # 16000 256