train:
    dataset: ThreeDPW
    subject: "outdoors_slalom_00_wo_off_surface"

    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8

    data_dir : outdoors_slalom_00/
    num_sample : 512 # 2048 256

valid:
    dataset: "ThreeDPWVal"
    subject: "outdoors_slalom_00_wo_off_surface"
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : outdoors_slalom_00/
    num_sample : -1
    pixel_per_batch: 512  # 16000 256

test:
    dataset: "ThreeDPWTest"
    subject: "outdoors_slalom_00_wo_off_surface"
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : outdoors_slalom_00/
    num_sample : -1
    pixel_per_batch: 1024