train:
    dataset: ThreeDPW
    subject: "Invisible_200to660_w_insurf"
    start_frame: 200
    end_frame: 660
    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8

    data_dir : Invisible/
    num_sample : 512 # 2048 256

valid:
    dataset: "ThreeDPWVal"
    subject: "Invisible_200to660_w_insurf"
    start_frame: 200
    end_frame: 660
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : Invisible/
    num_sample : -1
    pixel_per_batch: 512  # 16000 256

test:
    dataset: "ThreeDPWTest"
    subject: "Invisible_200to660_w_insurf"
    start_frame: 200
    end_frame: 660
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : Invisible/
    num_sample : -1
    pixel_per_batch: 1024