train:
    dataset: Hi4D
#    subject: "courtyard_shakeHands_00_no_pose_condition_interpenetration_loss_idr"
    subject: "triple02_dance02_88_ratio75_personid"
    start_frame: 0
    end_frame: 240
    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8
    num_person: 3
    data_dir : triple02_dance02_88/
    num_sample : 256 # 256
    using_SAM: True
    ratio_uncertain: 0.5

valid:
    dataset: "Hi4DVal"
#    subject: "courtyard_shakeHands_00_no_pose_condition_interpenetration_loss_idr"
    subject: "triple02_dance02_88_ratio75_personid"
    start_frame: 0
    end_frame: 240
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : triple02_dance02_88/
    num_sample : -1
    pixel_per_batch: 1024 # 1024
    using_SAM: True
    ratio_uncertain: 0.5

test:
    dataset: "Hi4DTest"
#    subject: "courtyard_shakeHands_00_no_pose_condition_interpenetration_loss_idr"
    subject: "triple02_dance02_88_ratio75_personid"
    start_frame: 0
    end_frame: 240
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 0

    data_dir : triple02_dance02_88/
    num_sample : 0
    pixel_per_batch: 1024 # 1024
    using_SAM: True
    ratio_uncertain: 0.5