train:
    dataset: Hi4D
#    subject: "courtyard_shakeHands_00_no_pose_condition_interpenetration_loss_idr"
    subject: "two_soccer_sam_ratio75_smpl_surface_earlystop"
    start_frame: 0
    end_frame: 95
    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8
    num_person: 2
    data_dir : two_soccer/
    num_sample : 512
    using_SAM: True
    ratio_uncertain: 0.75

valid:
    dataset: "Hi4DVal"
#    subject: "courtyard_shakeHands_00_no_pose_condition_interpenetration_loss_idr"
    subject: "two_soccer_sam_ratio75_smpl_surface_earlystop"
    start_frame: 0
    end_frame: 95
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : two_soccer/
    num_sample : -1
    pixel_per_batch: 2048
    using_SAM: True
    ratio_uncertain: 0.75

test:
    dataset: "Hi4DTest"
#    subject: "courtyard_shakeHands_00_no_pose_condition_interpenetration_loss_idr"
    subject: "two_soccer_sam_ratio75_smpl_surface_earlystop"
    start_frame: 0
    end_frame: 95
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 0

    data_dir : two_soccer/
    num_sample : 0
    pixel_per_batch: 1024
    using_SAM: True
    ratio_uncertain: 0.75