train:
    dataset: ThreeDPW
    subject: "parkinglot_release_new_loss_bg_frame"
    start_frame: 0
    end_frame: 42
    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8

    data_dir : parkinglot/
    num_sample : 512 

valid:
    dataset: "ThreeDPWVal"
    subject: "parkinglot_release_new_loss_bg_frame"
    start_frame: 0
    end_frame: 42
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    data_dir : parkinglot/
    num_sample : -1
    pixel_per_batch: 2048 

test:
    dataset: "ThreeDPWTest"
    subject: "parkinglot_release_new_loss_bg_frame"
    start_frame: 0
    end_frame: 42
    image_id: 0

    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 0

    data_dir : parkinglot/
    num_sample : 0
    pixel_per_batch: 2048